import { Dimensions, StyleSheet } from 'react-native';

const WINDOW_WIDTH = Dimensions.get('window').width;

export default StyleSheet.create({
  container: {
    backgroundColor: '#1B1F20',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: '100%',
  },
  timingBar: {
    alignSelf: 'flex-end',
    backgroundColor: '#31CB94',
    height: 3,
  },
  recordingBar: {
    alignSelf: 'flex-start',
    backgroundColor: '#31CB94',
    height: 3,
    width: 1,
  },
  timingBarShadow: {
    alignSelf: 'flex-end',
    borderBottomColor: '#31CB94',
    width: WINDOW_WIDTH,
    borderBottomWidth: 1,
    height: 0,
  },
  fileName: {
    borderColor: 'white',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
    marginTop: 100,
    marginRight: 20,
    marginLeft: 20,
    height: 28,
  },
  fileNameInput: {
    color: 'white',
    flex: 1,
    fontSize: 18,
    textAlign: 'center',
    marginHorizontal: 40,
  },
  progressText: {
    fontSize: 24,
    color: 'white',
    width: 125,
  },
  recordButton: {
    backgroundColor: '#E8163E',
    borderRadius: 30,
    height: 60,
    width: 60,
  },
  playPauseIcon: {
    flex: 1,
    width: 80,
    height: 80,
    borderRadius: 40,
    alignSelf: 'center',
  },
  stopButton: {
    backgroundColor: '#E8163E',
    height: 60,
    width: 60,
  },
  saveButton: {
    backgroundColor: '#31CB94',
    borderRadius: 4,
    flex: 1,
    height: 50,
    padding: 4,
    paddingHorizontal: 50,
    marginHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 18,
  },
  cancelButton: {
    borderColor: '#E8163E',
    borderWidth: 1,
    borderRadius: 4,
    flex: 1,
    height: 50,
    padding: 4,
    marginHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    color: '#E8163E',
    textAlign: 'center',
    fontSize: 18,
  },
  navBar: {
    top: 0,
    right: 0,
    left: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E8163E',
    height: 50,
  },
  navTitle: {
    padding: 10,
    color: 'white',
    fontSize: 20,
    marginLeft: 10,
    marginRight: 10,
  },
  detailsContainer: {
    flexDirection: 'row',
    height: 100,
    padding: 20,
    width: '100%',
  },
  buttonContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    width: 40,
    marginHorizontal: 20,
  },
  saveContainer: {
    width: 200,
    height: 40,
    marginTop: 10,
    marginBottom: 50,
  },
  progressTextContainer: {
    height: 40,
    justifyContent: 'center',
  },
  modalContainer: {
    backgroundColor: 'white',
    opacity: 0.4,
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 2,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal: {
    backgroundColor: 'blue',
    height: 200,
    width: 200,
  },
});
